---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fbanna.
--- DateTime: 9/1/25 2:24 PM
---
-- In this file we shall parse the path parameter at first
local bundle = eocto.getPathParam("bundle")
if bundle ~= nil and
        string.len(bundle) > 0 and
        (
                tonumber(bundle) == 1 or
                        tonumber(bundle) == 3 or
                        tonumber(bundle) == 5 or
                        tonumber(bundle) == 10
        ) then
    eocto.debug("info",string.format("we got a bundle of %s",bundle))
    eocto.render("pvcards/partials/memberships/con",{})
else
    eocto.debug("error",string.format("Unknown bundle %s",bundle))
end