---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fbanna.
--- DateTime: 9/25/25 6:15 PM
---

--[[
    This module loads mining images from the configured directory
    and returns their names as a Lua table based on configuration
]]

local pp = require('views.utils.prettyPrinter')

local IMAGE_CONFIG = {
    directory = "views/payments/public/images/mining",
    relativePath = "images/mining/",
    extension = ".webp",
    mapping = {
        ["101"] = {
            ["name"] = "Miner Sentinel",
            ["grade"] = "C-",
            ["price"] = 100
        },
        ["102"] = {
            ["name"] = "ASIC Alchemist",
            ["grade"] = "C",
            ["price"] = 300
        },
        ["103"] = {
            ["name"] = "Bit Bulldozer",
            ["grade"] = "C+",
            ["price"] = 500
        },
        ["104"] = {
            ["name"] = "Hash Forge",
            ["grade"] = "C++",
            ["price"] = 1000
        },
        ["105"] = {
            ["name"] = "Crypto Digger",
            ["grade"] = "B-",
            ["price"] = 2500
        },
        ["106"] = {
            ["name"] = "Minor Maven",
            ["grade"] = "B",
            ["price"] = 5000
        },
        ["107"] = {
            ["name"] = "Node Navigator",
            ["grade"] = "B+",
            ["price"] = 10000
        },
        ["108"] = {
            ["name"] = "Hash Harvester",
            ["grade"] = "B++",
            ["price"] = 15000
        },
        ["109"] = {
            ["name"] = "Coin Crafter",
            ["grade"] = "A-",
            ["price"] = 20000
        },
        ["110"] = {
            ["name"] = "Rig Master",
            ["grade"] = "A",
            ["price"] = 30000
        },
        ["111"] = {
            ["name"] = "Block Commander",
            ["grade"] = "A+",
            ["price"] = 50000
        },
        ["112"] = {
            ["name"] = "Hashrate Hero",
            ["grade"] = "A++",
            ["price"] = 100000
        }
        --["113"] = {
        --    ["name"] = "The Guardian King",
        --    ["grade"] = "K★"
        --},
        --["114"] = {
        --    ["name"] = "The Builder King",
        --    ["grade"] = "K★★"
        --},
        --["115"] = {
        --    ["name"] = "The Commander King",
        --    ["grade"] = "K★★★"
        --},
        --["116"] = {
        --    ["name"] = "The Visionary King",
        --    ["grade"] = "K★★★★"
        --},
        --["117"] = {
        --    ["name"] = "The Supreme King",
        --    ["grade"] = "K★★★★★"
        --}
    }
}
eocto.setLocal("eds",IMAGE_CONFIG)
--pp.print(IMAGE_CONFIG)