---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fbanna.
--- DateTime: 10/7/25 3:18 PM
---
local pp = require("views.utils.prettyPrinter")
local conversions = require("views.utils.conversions")
local conversionRate = conversions.getConversionRate()
local params = eocto.getQueryParams()
if params["membership"] ~= nil then
    local membership = tonumber(params["membership"])
    eocto.setLocal("amount", membership)
    eocto.setLocal("period", params["period"])
    eocto.setSession("membership", tonumber(params["membership"]))
    eocto.setSession("membershipPeriod", params["period"])
    local CurrentEDS = eocto.getSession("package")
    local toBePaid = (CurrentEDS["price"] + 5 + membership) * 1.0153 * conversions.getConversionRate()
    eocto.setLocal("toBePaid", toBePaid)
    local bridgeFees = toBePaid*0.005
    local swapFees = bridgeFees*0.01
    local totalFees = conversions.convertUSDToeAI(conversionRate,bridgeFees+swapFees) + membership
    eocto.setLocal("toBePaid",toBePaid)
    eocto.setLocal("bridgeFees",bridgeFees)
    eocto.setLocal("swapFees",swapFees)
    eocto.setLocal("totalFees",totalFees)
end
